### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by lmcreate** [YueNing/python#1]
您好，请问你是恒天的员工吗？我们这边在搜索hengtiansoft时有搜索到您，想咨询下，你这边上传的代码中有包含公司内容的信息吗？还请回复下，非常感谢。

**Comment by YueNing** [comment]
你是

**Comment by lmcreate** [comment]
我这边是恒天的，因为搜索到您上传的内容可能包含公司的敏感信息，所以想向您咨询下

**Comment by YueNing** [comment]
哦哦  这样啊 没有的 就之前实习无聊自己学着写Python留下来的 应该是redeme里面有hengtian的拼音的关系 和公司没关系得东西 应该能瞧出来 代码这么low 哈哈 都是网上初级的东西

**Comment by YueNing** [comment]
都N年前的事情了 你也真是尽职尽责 哈哈哈
